StylesPath = .config/vale/styles
# TODO: Change `MinAlertLevel` to the default `suggestion` and figure out how to get the CLI to return a non-zero exit code.
MinAlertLevel = error
Vocab = Terminology
Packages = Google

[*.{md,mdx}]
BasedOnStyles = Vale, Google
