name: Check Pull Request Title

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  insight:
    name: Insight
    if: ${{ github.event.action == 'opened' || github.event.changes.title != null }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Insight
        uses: arghena/insight@8cc65ddff8c3d2b20647171ef489824c88889357 # v0.1.0-canary.55
        with:
          check-pull-request-title: true
