name: Check Pull Request Title

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number }}
  cancel-in-progress: true

on:
  pull_request:
    types: [opened, edited]

permissions:
  contents: read

jobs:
  insight:
    name: Insight
    if: ${{ github.event.action == 'opened' || github.event.changes.title != null }}
    runs-on: ubuntu-latest
    steps:
      - name: Run Insight
        uses: arghena/insight@2b2f5097b7d9e1ce56bc8a025d3987df3ff054e0 # v0.1.0-canary.56
        with:
          check-pull-request-title: true
