name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: [canary]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mdx'
      - '**/*.css'
      - '**/package.json'
      - '**/pnpm-lock.yaml'
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mdx'
      - '**/*.css'
      - '**/package.json'
      - '**/pnpm-lock.yaml'

permissions:
  contents: read

jobs:
  # TODO: Waiting for bundle-analyzer to support Turbopack.
  # https://github.com/codecov/codecov-javascript-bundler-plugins/issues/251
  build-check:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Setup Node and pnpm
        # NOTE: `--frozen-lockfile` is `true` by default in CI.
        # https://pnpm.io/cli/install#--frozen-lockfile
        uses: pnpm/setup@84cb39b217b10273981911c288cd62326dc7c6d2 # v2.0.2
      - name: Build
        run: pnpm build
        env:
          NEXT_TELEMETRY_DISABLED: 1
