name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref_name }}
  cancel-in-progress: true

on:
  push:
    branches: [canary]
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mdx'
      - '**/*.css'
      - '**/package.json'
      - '**/pnpm-lock.yaml'
  pull_request:
    paths:
      - '**/*.ts'
      - '**/*.tsx'
      - '**/*.mdx'
      - '**/*.css'
      - '**/package.json'
      - '**/pnpm-lock.yaml'

permissions:
  contents: read

jobs:
  # TODO: Waiting for bundle-analyzer to support Turbopack.
  # https://github.com/codecov/codecov-javascript-bundler-plugins/issues/251
  build-check:
    name: Build check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Setup Node and pnpm
        uses: pnpm/setup@703c52620218391530e48b9e8870d5c0082e1b9b # v2.1.0
        with:
          require-lockfile: true
          # cache: true
          # cache-save-if: ${{ github.ref_name == 'canary' }}
      - name: Build
        run: pnpm build
        env:
          NEXT_TELEMETRY_DISABLED: 1
