name: Lock Threads

on:
  schedule:
    # Runs daily.
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  lock-threads:
    permissions:
      issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    name: Run lock threads
    if: ${{ github.repository_owner == 'arghena' }}
    steps:
      - name: Lock threads
        uses: dessant/lock-threads@89ae32b08ed1a541efecbab17912962a5e38981c # v6.0.2
        with:
          add-issue-labels: 'locked'
          add-pr-labels: 'locked'
          issue-inactive-days: 14
          issue-comment: This closed issue has been automatically locked because it had no new activity for 2 weeks.
          pr-inactive-days: 14
          log-output: true
